# Default values for monitoring-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: monitoring

prometheus:
  label: 
    app: prometheus-server
  clusterRole:
    name: prometheus
  configMap:
    name: prometheus-server-conf
    filename: prometheus.yml
    labels:
      name: prometheus
  service:
    type: ClusterIP
    name: prometheus-service
    port: 8080
    nodePort: 30000
  deployment:
    name: prometheus-deployment
    replicas: 1
    containers:
      name: prometheus
      image: prom/prometheus
      port: 9090
    configLocation: /etc/prometheus
    volume:
      - name: prometheus-config-volume
        mountPath: /etc/prometheus/
      - name: prometheus-storage-volume
        mountPath: /prometheus/

kubeStateMetrics:
  namespace: kube-system
  name: kube-state-metrics
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: v1.8.0
  service:
    ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
    - name: telemetry
      port: 8081
      targetPort: telemetry
    selector:
      app.kubernetes.io/name: kube-state-metrics
  deployment:
    replicas: 1
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
    containers:
      image: quay.io/coreos/kube-state-metrics:v1.8.0
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /
          port: 8081
        initialDelaySeconds: 5
        timeoutSeconds: 5
      ports:
      - containerPort: 8080
        name: http-metrics
      - containerPort: 8081
        name: telemetry
    nodeSelector:
      kubernetes.io/os: linux
      
nodeExporter:
  name: node-exporter
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
  service:
    type: NodePort
    nodePort: 30080
  deployment:
    containers:
      image: prom/node-exporter
      port: 9100
      volumeMounts:
        - mountPath: /host/sys
          # mountPropagation: HostToContainer (https://github.com/prometheus-community/helm-charts/issues/467#issuecomment-957091174)
          name: sys
          readOnly: true
        - mountPath: /host/root
          mountPropagation: HostToContainer
          name: root
          readOnly: true
    volumes:
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /
        name: root



    

    
    
