# Default values for monitoring-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: monitoring

prometheus:
  label: 
    app: prometheus-server
  clusterRole:
    name: prometheus
  configMap:
    name: prometheus-server-conf
    filename: prometheus.yml
    labels:
      name: prometheus
  service:
    type: ClusterIP
    name: prometheus-service
    port: 8080
    nodePort: 30000
  deployment:
    name: prometheus-deployment
    replicas: 1
    containers:
      name: prometheus
      image: prom/prometheus
      port: 9090
    configLocation: /etc/prometheus
    volume:
      - name: prometheus-config-volume
        mountPath: /etc/prometheus/
      - name: prometheus-storage-volume
        mountPath: /prometheus/

kubeStateMetrics:
  namespace: kube-system
  name: kube-state-metrics
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: v1.8.0
  service:
    ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
    - name: telemetry
      port: 8081
      targetPort: telemetry
    selector:
      app.kubernetes.io/name: kube-state-metrics

  deployment:
    replicas: 1
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
    containers:
      image: quay.io/coreos/kube-state-metrics:v1.8.0
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /
          port: 8081
        initialDelaySeconds: 5
        timeoutSeconds: 5
      ports:
      - containerPort: 8080
        name: http-metrics
      - containerPort: 8081
        name: telemetry
    nodeSelector:
      kubernetes.io/os: linux
    

    
    


    

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
