apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: {{ include "kubesm.labels" . | nindent 4 }}
  name: {{ .Values.kubeStateMetrics.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.kubeStateMetrics.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.kubeStateMetrics.name }}
  namespace: {{ .Values.kubeStateMetrics.namespace }}
