apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.configMap.name }}
  labels:
    name: {{ .Values.prometheus.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  {{ include "prometheus.cm.config" . }}
