apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Values.prometheus.clusterRole.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.prometheus.clusterRole.name }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.namespace }}
